### PR TITLE
Note that Firefox Send is currently offline

### PR DESCRIPTION
**Pull request by KTibow**
Add a README notice. Some tests will fail as a result of this.
Is self-hosted Firefox Send offline for what you know, **nneonneo**?
Also this causes tests to fail, too...

### CODE REVIEW

**Comment by nneonneo** [comment]
Thanks for the patch. However, unless the outage is much longer-lasting, I don't think it's necessary to mention this in the README for now - just like you wouldn't normally mention a service outage in an API client repo. Not merging this for now - will reconsider if the outage last longer than a month or so.

**Comment by KTibow** [comment]
Okay, sounds good. Although the library may need a restructure, as according to https://www.techspot.com/news/85979-mozilla-temporarily-shuts-down-firefox-send-response-malware.html:

> when Send returns, you'll be required to sign in with a Firefox account to upload content.

**Comment by nneonneo** [comment]
Good to know. I already prepared some changes (not pushed yet) for using a Firefox Account. Hopefully the flow is still roughly the same after their changes.

**Comment by KTibow** [comment]
Aw, come on, Firefox.
https://support.mozilla.org/en-US/kb/what-happened-firefox-send

**Pull request closed without merging**
