### PR TITLE
Fix a minor bug not detected by unit tests

### PR DESCRIPTION
**Pull request by persmule**
I forgot to change the way to call set_params in do_set_params after
changing the difinition of set_params. Now it get fixed.

All existing unit tests is passed.

### CODE REVIEW

**Comment by nneonneo** [comment]
Thanks! Would you mind adding a regression/unit test that can exercise this case? That way we can be sure it won’t break in the future. 

Much thanks for catching this.

**Comment by persmule** [comment]
Since do_set_params() is defined inside main(), how can I write test cases for it?

**Comment by persmule** [comment]
In this revision, I have written a test case for main() suitable to
test do_set_params().

**Comment by nneonneo** [comment]
LGTM - thanks again for your contributions!

**Pull request merged**
