### PR TITLE
Add the capability to use other send service

### PR DESCRIPTION
**Pull request by persmule**
e.g. testing services listed in
https://github.com/mozilla/send#testing

### CODE REVIEW

**Comment by nneonneo** [comment]
Looks great. How was it tested?

**Comment by persmule** [comment]
> How was it tested?
e.g. using service https://send.dev.mozaws.net/

**Comment by persmule** [comment]
Now I have modified the unit tests and all test passed.

**Comment by nneonneo** [comment]
Thanks. A few things:

- The tests fail if I use `send.stage.mozaws.net`, but succeed on `send.firefox.com`. Do you know why?
- Can the tests be made to run against https://send.firefox.com, https://send.stage.mozaws.net and https://send.dev.mozaws.net? The easiest way to do this is probably to make `TestFFSend` a base class and in each derived class define a class variable which specifies the service to use.
- Can you add a slash to `args.service` if it's missing, so that it is possible to specify `-s https://send.firefox.com` and not have that fail?

Otherwise, it looks good - I tested against both Python 2.7 and Python 3.6 and everything works out. Thanks for your contribution!

**Comment by nneonneo** [comment]
OK, never mind about send.stage - it's broken right now (the client attempts to connect to a websocket at /api/ws which throws a 404, and the original API code I interact with appears to be different somehow so the MAC checks fail).

**Comment by persmule** [comment]
I have tried to assign service from command line for testcase, but failed.

Now for testcase, service can be assigned via environment variable.
e.g. `$ SERVICE=https://send.dev.mozaws.net python3 test_ffsend.py`

https://send.firefox.com/ remains the default value for testcase if environment variable SERVICE is absent.

In this commit, the separator '/' will automatically be appended at
the end of service string if it is absent there.

**Pull request merged**
